FROM ros-ubuntu:14.04

RUN cd ~ && \
    wget -q https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.0rc2.tar.gz && \
    tar zxf pcl-1.8.0rc2.tar.gz

RUN cd ~/pcl-pcl-1.8.0rc2 && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j2 && \
    sudo make install

RUN mkdir -p ~/ros/ws_jsk_recognition/src && \
    cd ~/ros/ws_jsk_recognition/src && \
    sudo apt-get install -y python-rosinstall-generator python-wstool && \
    rosinstall_generator --tar --rosdistro indigo \
        pcl_conversions \
        pcl_ros \
        octomap_server \
        > .rosinstall && \
    wstool up -j -1

RUN cd ~/ros/ws_jsk_recognition/src && \
    rosdep update --include-eol-distros && \
    rosdep install --from-path . -y -i

RUN cd ~/ros/ws_jsk_recognition && \
    sudo apt-get install -y python-catkin-tools && \
    . /opt/ros/indigo/setup.sh && \
    catkin build

RUN sudo apt-get install -y python-vtk tcl-vtk
RUN sudo apt-get install -y ros-indigo-pcl-conversions ros-indigo-pcl-ros ros-indigo-octomap-server
RUN sudo apt-get install -y ros-indigo-rviz ros-indigo-robot-self-filter ros-indigo-moveit-ros-perception
RUN sudo apt-get install -y libopencv-dev liblapack-dev
RUN sudo apt-get install -y emacs cython
RUN rosdep update --include-eol-distros
RUN rosdep resolve gtk2 | sed -e "s/^#.*//g" | xargs sudo apt-get install -y # image_view
RUN rosdep resolve python-qt-bindings | sed -e "s/^#.*//g" | xargs sudo apt-get install -y # qt_gui_core
RUN rosdep resolve libqt5-gui | sed -e "s/^#.*//g" | xargs sudo apt-get install -y # libqt5-gui
RUN rosdep resolve qt5-qmake | sed -e "s/^#.*//g" | xargs sudo apt-get install -y # qt5-qmake
RUN rosdep resolve python-h5py | sed -e "s/^#.*//g" | xargs sudo apt-get install -y # python-h5py
RUN sudo apt-get install -y octave festival

# fix latest pip install fcn errors
RUN curl https://bootstrap.pypa.io/get-pip.py | sudo python -; sudo -H pip install 'pip<10'
RUN sudo apt install -y python-tornado # pip installed tornado (5.1.1) fails on 14.04
RUN sudo pip install fcn chainercv chainer==6.7.0 cupy-cuda91

# install common package to speedup
RUN sudo pip install freezegun
RUN sudo apt-get install -y libshiboken-dev shiboken \
                                python-qt4 python-qt4-dev python-sip-dev libvtk-java \
                                libgtk2.0-dev \
                                python-pyside libpyside-dev \
                                ros-indigo-rqt-reconfigure python-matplotlib imagemagick \
                                python-rosinstall-generator python-wstool \
                                ros-indigo-pcl-msgs ros-indigo-octomap-msgs
