FROM ros:indigo-ros-base

RUN apt-get update && apt-get dist-upgrade -y

RUN apt-get update && apt-get install -y \
    wget \
    libboost-all-dev \
    libeigen3-dev \
    libflann-dev \
    libqhull-dev \
    libvtk5-dev

RUN apt-get update && apt-get install -y python-vtk tcl-vtk

RUN apt-get update && apt-get install -y python-pip
RUN pip install -U dlib

RUN apt-get update && apt-get install -y curl git wget sudo lsb-release ccache apt-cacher-ng patch man-db
RUN apt-get update && apt-get install -y mesa-utils
RUN apt-get update && apt-get install -y --force-yes -q -qq mongodb-clients mongodb-server -o Dpkg::Options::=--force-confdef

## setup EoL repository for jade
RUN echo "deb http://snapshots.ros.org/jade/final/ubuntu `lsb_release -sc` main" >> /etc/apt/sources.list.d/ros-latest.list
RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0xCBF125EA
RUN apt-get update && apt-get install -y ros-jade-ros-base
##

RUN addgroup --gid 976 jenkins
RUN adduser --uid 983 --disabled-password --gecos "" --force-badname --ingroup jenkins user

RUN sed -i '/^%sudo/ a user ALL=(ALL) NOPASSWD: ALL' /etc/sudoers

USER user
