FROM ros-ubuntu:14.04

RUN cd ~ && \
    wget -q https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.0rc2.tar.gz && \
    tar zxf pcl-1.8.0rc2.tar.gz

RUN cd ~/pcl-pcl-1.8.0rc2 && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j2 && \
    sudo make install

RUN mkdir -p ~/ros/ws_jsk_recognition/src && \
    cd ~/ros/ws_jsk_recognition/src && \
    sudo apt-get install -y python-rosinstall-generator python-wstool && \
    rosinstall_generator --tar --rosdistro indigo \
        pcl_conversions \
        pcl_ros \
        octomap_server \
        > .rosinstall && \
    wstool up -j -1

RUN cd ~/ros/ws_jsk_recognition/src && \
    rosdep update --include-eol-distros && \
    rosdep install --from-path . -y -i

RUN cd ~/ros/ws_jsk_recognition && \
    sudo apt-get install -y python-catkin-tools && \
    . /opt/ros/indigo/setup.sh && \
    catkin build

RUN sudo apt-get install -y python-vtk tcl-vtk

# https://github.com/moby/moby/issues/1996#issuecomment-185872769
ARG CACHEBUST=1
RUN sudo apt-get update && sudo apt-get dist-upgrade -y
