FROM ros:melodic-ros-base

RUN apt-get update && apt-get dist-upgrade -y

RUN apt-get update && apt-get install -y \
    wget \
    libboost-all-dev \
    libeigen3-dev \
    libflann-dev \
    libqhull-dev \
    libvtk6-dev

RUN apt-get update && apt-get install -y python-pip
RUN pip install -U dlib==19.22.0

RUN apt-get update && apt-get install -y curl git wget sudo lsb-release ccache apt-cacher-ng patch man-db
RUN apt-get update && apt-get install -y mesa-utils
RUN apt-get update && apt-get install -y --force-yes -q -qq mongodb-clients mongodb-server -o Dpkg::Options::=--force-confdef


RUN addgroup --gid 976 jenkins
RUN adduser --uid 983 --disabled-password --gecos "" --force-badname --ingroup jenkins user

RUN sed -i '/^%sudo/ a user ALL=(ALL) NOPASSWD: ALL' /etc/sudoers

USER user
